routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
	return view('welcome');
});

Route::namespace('Admin')->prefix('admin')->group(function () {
    Route::get('home', 'HomeController@index')->name('admin.home.index');
    Route::get('cache', 'CacheController@index')->name('admin.cache.index');
    Route::delete('cache/{key}', 'CacheController@destroy')->name('admin.cache.destroy');
});

Route::namespace('App')->prefix('home')->group(function () {
    Route::get('', 'HomeController@index')->name('app.home.index');
    Route::get('cart', 'CartController@index')->name('app.cart.index');
    Route::patch('cart/{id}', 'CartController@update')->name('app.cart.update');
    Route::delete('cart/{id}', 'CartController@destroy')->name('app.cart.destroy');
    Route::get('products', 'ProductController@index')->name('app.product.index');
    Route::post('cart/{product}', 'CartController@store')->name('app.cart.store');

    Route::resource('addresses', 'AddressController', ['as' => 'app'])->except(['show']);

	Auth::routes();
});

resources/views/app/templates/partials/navigation.blade.php
<fieldset>
	<ul>
		@guest
			<li><a href="{{ route('login') }}">Login</a></li>
			<li><a href="{{ route('register') }}">Register</a></li>
		@else
			@if($administrator)
				<li><a href="{{ route('admin.home.index') }}">Admin Panel</a></li>
			@endif
			<li><a href="{{ route('logout') }}"
				onclick="event.preventDefault();
						document.getElementById('logout-form').submit();">
				Logout
			</a></li>
			<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
				{{ csrf_field() }}
			</form>
		@endguest
	</ul>
</fieldset>

<fieldset>
	<legend>Navigation</legend>
	<ul>
		<li><a href="{{ route('app.home.index') }}">Home</a></li>
		<li><a href="{{ route('app.cart.index') }}">Cart</a></li>
		<li><a href="{{ route('app.product.index') }}">Products</a></li>
		<li><a href="{{ route('app.addresses.index') }}">Address</a></li>
	</ul>
</fieldset>